language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_script:
  - pip install coveralls
install:
  - python setup.py install
script:
  - coverage run --source=chronyk test.py
after_success:
  - coveralls
